var paragraph = document.getElementById("myParagraph");

var arabic = "الذكاء الاصطناعي (AI) هو فرع من علوم الكمبيوتر يهدف إلى إنشاء أنظمة قادرة على محاكاة الذكاء البشري. يتضمن ذلك تطوير خوارزميات تمكّن الآلات من التعلم والتفكير والتكيف مع البيئات المختلفة. منذ بداياته، شهد الذكاء الاصطناعي تطورًا كبيرًا، حيث انتقل من معالجة البيانات البسيطة إلى تقنيات معقدة مثل التعلم العميق والشبكات العصبية. تُستخدم تطبيقات الذكاء الاصطناعي في العديد من المجالات، مثل الرعاية الصحية، حيث يمكنها تحليل البيانات الطبية وتقديم تشخيصات دقيقة. في مجال السيارات، يساهم الذكاء الاصطناعي في تطوير القيادة الذاتية وتحسين أنظمة الأمان. كما يُستخدم في مجالات التسويق، حيث يتم تحليل سلوك المستهلك لتحسين الاستراتيجيات والإعلانات. تشمل التطبيقات الأخرى الذكاء الاصطناعي في التعليم، حيث يساعد في تخصيص المناهج الدراسية وفقًا لاحتياجات الطلاب. بالإضافة إلى ذلك، يُستخدم في الصناعات الإبداعية مثل الفن والموسيقى لتوليد محتوى جديد. تعتبر التحديات الأخلاقية من القضايا المهمة المرتبطة بالذكاء الاصطناعي، مثل الخصوصية والتحيز. كما أن هناك مخاوف من تأثيره على سوق العمل، حيث قد تؤدي الأتمتة إلى فقدان بعض الوظائف التقليدية. بالإضافة إلى ذلك، يعد الذكاء الاصطناعي أداة قوية في البحث العلمي، حيث يمكنه تحليل كميات هائلة من البيانات بشكل أسرع من البشر. بالمجمل، يُعد الذكاء الاصطناعي من أهم الاتجاهات التكنولوجية في العصر الحديث، ويمثل فرصة كبيرة للابتكار والتطور، رغم التحديات التي قد يواجهها.";

var english = "Artificial Intelligence (AI) is a branch of computer science aimed at creating systems capable of simulating human intelligence. This involves developing algorithms that enable machines to learn, think, and adapt to different environments. Since its inception, AI has undergone significant evolution, transitioning from simple data processing to complex techniques such as deep learning and neural networks.AI applications are utilized in various fields, such as healthcare, where they can analyze medical data and provide accurate diagnoses. In the automotive sector, AI contributes to the development of self-driving cars and improves safety systems. It is also used in marketing, analyzing consumer behavior to enhance strategies and advertisements.Other applications of AI include education, where it helps customize curricula according to students' needs. Additionally, it is employed in creative industries like art and music to generate new content.Ethical challenges are important issues associated with AI, such as privacy and bias. There are also concerns about its impact on the job market, as automation may lead to the loss of certain traditional jobs Furthermore, AI is a powerful tool in scientific research, capable of analyzing vast amounts of data faster than humans. Overall, AI is one of the most significant technological trends of the modern era, representing a major opportunity for innovation and development, despite the challenges it may face.";

function englishh() {
    paragraph.innerText = english;
};

function arabicc() {
    paragraph.innerText = arabic;
};